# Generated by Django 5.2.5 on 2026-01-21 18:18

from django.db import migrations
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile


def migrate_banners_to_postimages(apps, schema_editor):
    """Convert existing Post.banner images to PostImage objects"""
    Post = apps.get_model('posts', 'Post')
    PostImage = apps.get_model('posts', 'PostImage')
    
    for post in Post.objects.filter(banner__isnull=False).exclude(banner=''):
        # Create a PostImage object for each existing banner
        PostImage.objects.create(post=post, image=post.banner)


def reverse_migration(apps, schema_editor):
    """Optional: remove PostImage objects created from banners"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postimage'),
    ]

    operations = [
        migrations.RunPython(migrate_banners_to_postimages, reverse_migration),
    ]
