# Generated by Django 5.2.5 on 2026-01-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_migrate_banners_to_postimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='banner',
        ),
    ]
